version: '3.4'

services:
    zqh_dev:
        hostname: zqh_dev
        build:
            context: .
            dockerfile: Dockerfile
        expose: 
            - "22"
            - "80"
            - "443"
        ports: 
            - "50008:22"
        volumes: 
            - "/compiler/zhengqihang/workspace:/root/workspace"
            - "/data:/data"
            - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
        command: /bin/sh -c "while sleep 1000; do :; done"
        # fix gdb bug
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_PTRACE
        privileged: true